//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.EntityFramwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statement
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public string ChqNum { get; set; }
        public string Particulars { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Balance { get; set; }
        public string InitBranch { get; set; }
    }
}
